#! /bin/sh

chosen=$(printf "  Power Off\n  Restart\n  Suspend\n  Hibernate\n󰍃  Log Out\n  Lock" | rofi -dmenu -i -theme-str '@import "power.rasi"')


case "$chosen" in
	"  Power Off") i3exit shutdown ;;
	"  Restart")  i3exit reboot ;;
	"  Suspend") systemctl suspend ;;
	"  Hibernate") systemctl hibernate ;;
	"󰍃  Log Out") i3exit logout ;;
	"  Lock") betterlockscreen --lock dimblur ;;
	*) exit 1 ;;
esac
