[colors.bright]
black = "#3B4252"
blue = "#569CD6"
cyan = "#29B8DB"
green = "#9ece6a"
magenta = "#C586C0"
red = "#D54646"
white = "#ECEFF4"
yellow = "#D7BA7D"

[colors.normal]
black = "#3B4252"
blue = "#569CD6"
cyan = "#29B8DB"
green = "#9ece6a"
magenta = "#C586C0"
red = "#D54646"
white = "#abb2bf"
yellow = "#D7BA7D"

[colors.primary]
background = "#11121D"
foreground = "#D8DEE9"

[font]
size = 10.0

[font.bold]
family = "Fira Code Nerd Font"
style = "Bold"

[font.italic]
family = "Fira Code Nerd Font"
style = "Medium Italic"


[font.normal]
family = "Fira Code Nerd Font"
style = "Medium"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
opacity = 0.5

[window.dimensions]
columns = 112
lines = 28

[window.padding]
x = 0
y = 0
